version: '3.8'

services:
  go-api:
    container_name: admin-microservice-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:${PORT}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs/